name: SecureFace Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t secureface-api:ci .

      - name: Test Docker image exists
        run: docker images | grep secureface-api